### ISSUE TITLE
Searching for apps crashes the launcher

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/FP2-Launcher#24]
When I click the :mag: symbol, the search bar expands, but the launcher crashed immediately after that.

I'm using version 2.1 on Kitkat 4.4.2.

Can you reproduce this or do you need a log?

**Comment by Rudloff** [comment]
I can reproduce on Android 4.2.

Here is the stacktrace:
```
D/AndroidRuntime( 1477): Shutting down VM
W/dalvikvm( 1477): threadid=1: thread exiting with uncaught exception (group=0x3c2b3e10)
E/AndroidRuntime( 1477): FATAL EXCEPTION: main
E/AndroidRuntime( 1477): java.lang.NullPointerException
E/AndroidRuntime( 1477): 	at android.view.GLES20RenderLayer.redrawLater(GLES20RenderLayer.java:114)
E/AndroidRuntime( 1477): 	at android.view.View.getHardwareLayer(View.java:12406)
E/AndroidRuntime( 1477): 	at android.view.View.getDisplayList(View.java:12619)
E/AndroidRuntime( 1477): 	at android.view.View.getDisplayList(View.java:12694)
E/AndroidRuntime( 1477): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2910)
E/AndroidRuntime( 1477): 	at android.view.View.getDisplayList(View.java:12588)
E/AndroidRuntime( 1477): 	at android.view.View.getDisplayList(View.java:12694)
E/AndroidRuntime( 1477): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2910)
E/AndroidRuntime( 1477): 	at android.view.View.getDisplayList(View.java:12588)
E/AndroidRuntime( 1477): 	at android.view.View.getDisplayList(View.java:12694)
E/AndroidRuntime( 1477): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2910)
E/AndroidRuntime( 1477): 	at android.view.View.getDisplayList(View.java:12588)
E/AndroidRuntime( 1477): 	at android.view.View.getDisplayList(View.java:12694)
E/AndroidRuntime( 1477): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2910)
E/AndroidRuntime( 1477): 	at android.view.View.getDisplayList(View.java:12588)
E/AndroidRuntime( 1477): 	at android.view.View.getDisplayList(View.java:12694)
E/AndroidRuntime( 1477): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2910)
E/AndroidRuntime( 1477): 	at android.view.View.getDisplayList(View.java:12588)
E/AndroidRuntime( 1477): 	at android.view.View.getDisplayList(View.java:12694)
E/AndroidRuntime( 1477): 	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1198)
E/AndroidRuntime( 1477): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2176)
E/AndroidRuntime( 1477): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2048)
E/AndroidRuntime( 1477): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1857)
E/AndroidRuntime( 1477): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:992)
E/AndroidRuntime( 1477): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4376)
E/AndroidRuntime( 1477): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
E/AndroidRuntime( 1477): 	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
E/AndroidRuntime( 1477): 	at android.view.Choreographer.doFrame(Choreographer.java:561)
E/AndroidRuntime( 1477): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
E/AndroidRuntime( 1477): 	at android.os.Handler.handleCallback(Handler.java:725)
E/AndroidRuntime( 1477): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 1477): 	at android.os.Looper.loop(Looper.java:152)
E/AndroidRuntime( 1477): 	at android.app.ActivityThread.main(ActivityThread.java:5132)
E/AndroidRuntime( 1477): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1477): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 1477): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
E/AndroidRuntime( 1477): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
E/AndroidRuntime( 1477): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  396):   Force finishing activity community.fairphone.fplauncher3/com.fairphone.fplauncher3.Launcher
I/ActivityManager(  396): Clearing package preferred activities from community.fairphone.fplauncher3
```
